### ISSUE TITLE
Guide Feedback

### ISSUE THREAD

**Issue by frou** [Touchwonders/xcode-theme#1]
Thanks for the well written guide. It helped me 😀 

I'd like to offer two observations made while I ported an existing theme (from Sublime Text) to Xcode:

# 1
Even though I entered all my familiar battle-tested hex colours, the Xcode theme looked significantly different. It just had an overall washed out look to it.

Eventually I figured out that, before pasting each hex colour into the field in the Xcode colour picker, I first needed to click the gear icon and change the profile from `Generic RGB` to `sRGB`. After going through and re-pasting every colour with that extra step, the colours in syntax-highlighted code finally looked correct.

![hexcolour](https://user-images.githubusercontent.com/172663/67977514-2ad83700-fc10-11e9-942c-802f83c029a6.png)

# 2
It seems that there is a mysterious **Heading** syntax identifier which isn't mentioned in your guide.

What's mysterious about it is that it comes and goes from the `Fonts & Colours` section of the Xcode Preferences window. Sometimes it's there, sometimes it isn't. If I launch Xcode.app fresh and open the Preferences window, it's not there. But if I then close the Preferences window and immediately open it again, it is there:

<img width="644" alt="Screenshot 2019-10-31 at 18 42 19" src="https://user-images.githubusercontent.com/172663/67977999-07fa5280-fc11-11e9-886a-45ab2309a61c.png">

Whatever it is, it corresponds to the key `xcode.syntax.markup.code` in the `.xccolortheme` file.

-- Duncan

**Comment by toineheuvelmans** [comment]
Hi @frou, thank you for the extensive feedback! The `Heading` identifier is an interesting one 😅 I was planning to look into any changes in theming that might have been introduced in Xcode 11, so when I get to that, I'll make sure to look into this `Heading` one too.

**Comment by toineheuvelmans** [comment]
Hi @frou, there's an update on the post arriving very soon. I've been going through your feedback again. Two things:

I've been using [Skala Color](https://bjango.com/mac/skalacolor/) for years to be able to enter hex values, which doesn't specify a particular color profile. It turns out that all hex values I entered via Skala match the hex values in the dialog pane you shared above, when using the sRGB color profile 🤷‍♂ .

As for the `Heading`, indeed this is very mysterious, but I found that it is at least used for styling code blocks in Markdown files. I'll share the update blog post within a couple of days (needs internal review first) on our [blog](https://www.touchwonders.com/blog), with some more findings on `Heading` 😄
